Repository annnuuuh/whats-cookin, pull requests merged in 2021-09, with the labels that each got.

#18 Feature/wireframe
  src/classes/Recipe.js
  src/classes/RecipeRepository.js
  src/data/recipes.js
  src/index.html
  src/scripts.js
  src/styles.css
Labels: enhancement, planning

#24 Feature/search
  src/classes/Recipe.js
  src/classes/RecipeRepository.js
  src/index.html
  src/scripts.js
  src/styles.css
Labels: enhancement

#33 Feature/user data
  src/classes/RecipeRepository.js
  src/classes/User.js
  src/data/sample-user.js
  src/data/users.js
  src/index.html
  src/scripts.js
  src/styles.css
  test/User-test.js
Labels: enhancement

#35 Add styling to favorites and recipes to cook pages
  src/index.html
  src/scripts.js
  src/styles.css
Labels: enhancement

#38 Refactor/read me
  docs/README.md
  src/apiCalls.js
  src/classes/Ingredient.js
  src/scripts.js
Labels: documentation

#39 Feature/fetch
  src/apiCalls.js
  src/classes/Ingredient.js
  src/classes/Recipe.js
  src/data/ingredients.js
  src/data/recipes.js
  src/data/users.js
  src/scripts.js
Labels: enhancement

#40 Refactor/all
  src/apiCalls.js
  src/classes/RecipeRepository.js
  src/classes/User.js
  src/index.html
  src/scripts.js
  test/Ingredient-test.js
  test/Recipe-test.js
Labels: bug

#41 Add alt text to images
  src/index.html
  src/scripts.js
  src/styles.css
Labels: enhancement

#43 Bugfix/mocha test failure
  src/apiCalls.js
  src/classes/Ingredient.js
  src/classes/Recipe.js
  src/classes/RecipeRepository.js
  src/classes/User.js
  src/index.html
  src/scripts.js
Labels: bug

#58 Feature/pantry class
  src/apiCalls.js
  src/classes/Pantry.js
  src/classes/RecipeRepository.js
  src/classes/User.js
  src/data/sampleIngredientsData.js
  src/data/sampleRecipeData.js
  src/data/sampleUsersData.js
  src/domUpdates.js
  src/index.html
  src/scripts.js
  test/Ingredient-test.js
  test/Pantry-test.js
  test/Recipe-test.js
  test/RecipeRepository-test.js
  test/User-test.js
Labels: enhancement

#61 Refactor/fetch
  package-lock.json
  src/apiCalls.js
  src/classes/Pantry.js
  src/classes/User.js
  src/domUpdates.js
  src/scripts.js
Labels: enhancement

#62 Refactor/finishing touches
  src/classes/Recipe.js
  src/classes/RecipeRepository.js
  src/scripts.js
  test/Pantry-test.js
Labels: chore
